version: '3'

services:
  tahoo-mysql:
    image: mysql:latest
    container_name: tahoo-mysql
    volumes:
      - "./tahoo-mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tahoo_db
      MYSQL_USER: user_tahoo
      MYSQL_PASSWORD: 123456